// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Todo struct {
	ID        int64
	Title     string
	Content   string
	Createdat time.Time
}
